### ISSUE TITLE
Checklist not previewing as intended

### ISSUE THREAD

**Issue by LionelSelie** [Kholid060/MkDown2#269]
Hi there!

It seems the checklist is not showing tick boxes on the right-hand side, see [this screenshot](https://cdn.zappy.app/3b785b8b2913b916fa4992aef7fdc5de.png).

Thanks!

**Comment by Kholid060** [comment]
Hi, it has been fixed in 4bdc374cde2b419ec61df1fa4c148c554e0646b3
